//MAP
export const MAP_SUCCESS_GET = "MAP_SUCCESS_GET";
export const MAP_START_LOAD = "MAP_START_LOAD";
export const MAP_ERROR = "MAP_ERROR";
export const MAP_END_LOAD = "MAP_END_LOAD";
export const MAP_CLEAR_MARKER = "MAP_CLEAR_MARKER";
export const MAP_CLEAR_ERROR = "MAP_CLEAR_ERROR";
export const MAP_ADD_CENTER = "MAP_ADD_CENTER";

//AUTH
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_START_LOAD = "AUTH_START_LOAD";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";

//ADMIN
export const ADMIN_GET_USERS = "ADMIN_GET_USERS"